# Generated by Django 3.0.6 on 2020-08-26 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='home.jpg', upload_to='events/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique value for event page URL, created from name.', max_length=255, unique=True)),
                ('available', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='home.jpg', upload_to='listings/%Y/%m/%d')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(max_length=2555)),
                ('town', models.CharField(max_length=2555)),
                ('region', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('digital_address', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(related_name='Amenities', to='listing.Amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='home.jpg', upload_to='places/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique value for place page URL, created from name.', max_length=255, unique=True)),
                ('kind', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
                ('area', models.CharField(max_length=2555)),
                ('town', models.CharField(max_length=2555)),
                ('region', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='home.jpg', upload_to='listings/rooms/%Y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Unique value for room page URL, created from name.', max_length=255, unique=True)),
                ('available', models.BooleanField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='listing.Listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='place', to='listing.Place'),
        ),
    ]
