# Generated by Django 3.0.6 on 2020-08-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='place_ratings', to='listing.Rating'),
        ),
    ]
