# Generated by Django 3.0.6 on 2020-08-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200826_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
