# Generated by Django 3.0.6 on 2020-08-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
