# Generated by Django 3.0.6 on 2021-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='star_1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='star_2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='star_3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='star_4',
        ),
        migrations.RemoveField(
            model_name='place',
            name='star_5',
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
