# Generated by Django 3.0.6 on 2020-08-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_town_capital'),
        ('listing', '0011_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='region',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='town',
        ),
        migrations.RemoveField(
            model_name='place',
            name='area',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
        migrations.RemoveField(
            model_name='place',
            name='town',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_area', to='location.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_area', to='location.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Place_area', to='location.Area'),
            preserve_default=False,
        ),
    ]
