# Generated by Django 3.0.6 on 2020-08-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20200829_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='places',
        ),
    ]
