# Generated by Django 3.0.6 on 2020-08-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_remove_listing_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ImageField(blank=True, default='home.jpg', upload_to='amenities/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_amenity', to='listing.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='structure',
            field=models.ForeignKey(blank='True', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='structure_amenity', to='listing.Listing'),
            preserve_default=False,
        ),
    ]
