# Generated by Django 3.0.6 on 2020-08-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20200826_0836'),
        ('listing', '0011_listing_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('star_1', models.PositiveIntegerField(default=0)),
                ('star_2', models.PositiveIntegerField(default=0)),
                ('star_3', models.PositiveIntegerField(default=0)),
                ('star_4', models.PositiveIntegerField(default=0)),
                ('star_5', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_rating', to='listing.Place')),
                ('listing', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_rating', to='listing.Listing')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_rating', to='profiles.Profile')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_rating', to='listing.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
